### ISSUE TITLE
Support password way to authenticate

### ISSUE THREAD

**Issue by RockChinQ** [Soulter/hugging-chat-api#27]
Provide email/password method to login to the site to simplify the authentication.

**Comment by ogios** [comment]
i have that solved using simple requests
here's another version of api i just updated since i just found out that huggingchat has an update which requires user to sign in to use it: [huggingchat-api-Chinese.ver](https://github.com/ogios/huggingchat-api-Chinese.ver)
and i added mysql to save the sessions and conversations.
