### ISSUE TITLE
Getting the model without using api

### ISSUE THREAD

**Issue by AnaghaAMT** [Soulter/hugging-chat-api#29]
Is it possible to obtain the model alone as open source code without using the API so that it can be hosted on our server?

**Comment by ZKOussama7** [comment]
The Short Answer is "Of course you can",  it is supposed to be open source anyway.
---
the model is fine-tuned by LAION included in the open assistant project. but because of some Facebook's license shenanigans, since they are the ones who trained the original model called LLama, LAION are not allowed to distribute the fine-tuned ( modified) LLama models. 
### But
 What they are able to distribute is the XOR that you can use to change the Original Model to become Fine-tuned.
it is like distributing the multiplication (xor) of the original number (model) and their final number (model), so when you download the original number (model) and divide(xor again) the multiplication ( xor files )  by it you get the same final number (model) they made.

I worked on A and turned it into B, but i can give you neither, so i give you C=A*B, and you can get A by yourself, so you can recalculate B=C/A.

anyway Here is the link to the Xor Files of the same model used by hugging Chat:
[Open-Assist LLama-sft-6-llama-30b-xor model](https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor)
and here is what you need to know:
[The Most Important Thing](https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor/discussions/15)
and this is about the commercial use of those models:
[Important For Commercial Use](https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor/discussions/57)

**Comment by AnaghaAMT** [comment]
Hi,

Thank you for your attention to this matter.I am finding difficulty in what
is to be placed as input path and output path in this particular command:

python src/transformers/models/llama/convert_llama_weights_to_hf.py
--input_dir <input_path_llama_base>  --output_dir <output_path_llama30b_hf>
--model_size 30B

I understand xor_codec.py is the file used to perform xor operation and get
the original llama weights but unsure of what is to be provided as the
input path in this command.
I hope you will respond to this mail and guide me for the further steps.

Thanks ,
Anagha

**Comment by ZKOussama7** [comment]
i think it's something like this:
```
python src/transformers/models/llama/convert_llama_weights_to_hf.py
--input_dir /path/to/original/llama-30B-directory
--output_dir /path/to/output/llama-HF-directory
--model_size 30B
```

 - where original llama directory is the directory containing the base model as trained by facebook, that you should have downloaded already.

 - and output llama directory is the directory where you want the HF Llama model to be outputed to, this model is the one that you are going to use to with xor to get the finetuned model. like this:
---
```
python xor_codec.py
 oasst-sft-6-llama-30b/
 oasst-sft-6-llama-30b-xor/oasst-sft-6-llama-30b-xor/
 llama30b_hf/
```

where
 -  oasst-sft-6-llama-30b/: 
     - is the Final Model's Output Directory that you can use directly.
 -  oasst-sft-6-llama-30b-xor/oasst-sft-6-llama-30b-xor/ :
     -  is the model XOR that you can download from hugging face.
 -  llama30b_hf/ :
     -  is the HF Llama model that you have created using the first command.

I am not sure where you have difficulties.
Anyway you can always, if it's something I have an idea about.

**Comment by ZKOussama7** [comment]
if you have an organization/company then yes, I would take that route, if not then I am not even sure you would get permission at all.

and I already sent you this link: ( read it and you shall find your answer hhh )
```
and here is what you need to know:
```
[The Most Important Thing](https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor/discussions/15)

**Comment by ZKOussama7** [comment]
you are welcome.
the thing is... if you are not representing an organization, then i dont
see any problem with downloading the model I think, plus i recently found
multiple XORed ( people who already did the whole process ) models on
Huggingface, so if there was that much of a problem, they would have taken
them down.
on that note, search for
 ```
 Llama 6 sft oasst
or  Llama 7 sft oasst
```
on hugging face and you probably will find the fine-tuned models.
( ps: xor is not used for fine-tuning, it is used for encrypting, or
"modifying the weights to not distribute the originals", fine tuning is the
last phase of training a model where you basically teach it to do tasks )

**Comment by ZKOussama7** [comment]
here is the link for already XORed Llama 7 sft open assistant model, a better version ( more fine-tuned ) of huggingchat:
[HuggingChat Model Link](https://huggingface.co/TheBloke/OpenAssistant-SFT-7-Llama-30B-HF)

**Comment by AnaghaAMT** [comment]
Thanks, I'll check it out!

**Comment by Soulter** [comment]
We have implemented this feature. See README to get the usage.
